server:
  port: 8881

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: operation-service
          uri: lb://operation-service
          predicates:
            - Path=/api/operations/**

        - id: setting-service
          uri: lb://setting-service
          predicates:
            - Path=/api/settings/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
