server:
  port: 8881

spring:
  application:
    name: api-gateway-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
