server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        - id: operation-service
          uri: lb://OPERATION-SERVICE
          predicates:
            - Path=/api/operations/**

        - id: setting-service
          uri: lb://SETTING-SERVICE
          predicates:
            - Path=/api/settings/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
