server:
  port: 8081

spring:
  application:
    name: auth-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/auth_db
      database: auth_db

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
