server:
  port: ${AUTH_SERVICE_PORT}  # Port where the auth service will run

spring:
  application:
    name: auth-service  # Service name

  datasource:
    url: jdbc:postgresql://${POSTGRES_AUTH_HOST}:${POSTGRES_AUTH_PORT}/${POSTGRES_AUTH_DB}
    username: ${POSTGRES_AUTH_USER}
    password: ${POSTGRES_AUTH_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    register-with-eureka: true  # Register the auth service with Eureka
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:${DISCOVERY_PORT}/eureka/ # Eureka server URI
