server:
  port: ${CONFIG_PORT}   # Config service will run on port 8888

spring:
  application:
    name: config-service  # Name of your Spring Cloud Config server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/devloperHicham/config-data.git  # Git repository URL for configuration files
          default-label: main  # Use the 'main' branch for fetching configurations
