server:
  port: ${OPERATION_SERVICE_PORT}

spring:
  application:
    name: operation-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_OPERATION_HOST}:${POSTGRES_OPERATION_PORT}/${POSTGRES_OPERATION_DB}
    username: ${POSTGRES_OPERATION_USER}
    password: ${POSTGRES_OPERATION_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:${DISCOVERY_PORT}/eureka/
