server:
  port: 8083

spring:
  application:
    name: operation-service

  datasource:
    url: jdbc:postgresql://postgres-operation:5436/operation_db
    username: operation_user
    password: operation_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
