server:
  port: 8084

spring:
  application:
    name: setting-service

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://mongo:27017/setting_db}
      database: setting_db

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
