server:
  port: 8084

spring:
  application:
    name: setting-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/setting_db
      database: setting_db

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

