server:
  port: 8084

spring:
  application:
    name: setting-service

  datasource:
    url: jdbc:postgresql://postgres-setting:5432/setting_db
    username: setting_db
    password: setting_password12345@@
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
