server:
  port: 8082

spring:
  application:
    name: user-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/user_db
      database: user_db

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

