server:
  port: ${USER_SERVICE_PORT}

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_USER_HOST}:${POSTGRES_USER_PORT}/${POSTGRES_USER_DB}
    username: ${POSTGRES_USER_USER}
    password: ${POSTGRES_USER_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:${DISCOVERY_PORT}/eureka/

