server:
  port: 8082

spring:
  application:
    name: user-service

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://mongo:27017/user_db}
      database: user_db

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

